#!/usr/bin/env bash
# This script displays "Best School" 10 times using a while loop

# Initialize counter
counter=1

# Use while loop to repeat while counter is less than or equal to 10
while [ $counter -le 10 ]; do
    echo "Best School"
    counter=$((counter + 1))
done
